### ISSUE TITLE
YAML 1.2 spec: Example 7.1 - the order is inconvenient

### ISSUE THREAD

**Issue by asomov** [yaml/yaml#12]
The example 7.1 can be improved.
Some parsers (including SnakeYAML) try to keep the order if a map node by default (users may change it).
The example is about Alias and not about order in the map. The canonical YAML  can be changed to reflect the same order as in the example.
If the canonical is like this then SnakeYAML can use the canonical YAML in its tests (which is almost always the case):

```
%YAML 1.2

---
!!map {
  ? !!str "First occurrence"
  : &A !!str "Foo",
  ? !!str "Second occurrence"
  : *A,
  ? !!str "Override anchor"
  : &B !!str "Bar",
  ? !!str "Reuse anchor"
  : *B,
}
```

**Comment by orenbenkiki** [comment]
Actually order is key to this example because anchors and aliases _do_
depend on the order. Since an implementation is not expected to preserve
the order it follows that it may need to modify the anchors, so you also
can't rely on them being preserved. It is in general "very bad practice" to
rely on the order of map keys.

**Comment by asomov** [comment]
1) the example is not about order of keys in map
2) if it is changed from map to sequence the issue is solved
3) every example must not be more complex then it is required for the test case
4) if there is no real application which is using the examples as they are, the examples have less value
5) I think to help developers to implement the spec is more important then to discuss unrelated practices
6) if the order is important or not should be tested in a separate test case
7) the amount of questions is now so high that any obstacle reduces a chance to get a Java implementation of YAML 1.2

If all the above is not important enough to make a minor change, then I have no other arguments.

**Comment by flyx** [comment]
> If the canonical is like this then SnakeYAML can use the canonical YAML in its tests (which is almost always the case):

If you are checking the actual output of parsing against the expected output by transforming it back to a YAML stream and then comparing it, you
- test an unrelated component (the presenter)
- have a test that tests against specs of your implementation and not the YAML specification

I think these are flaws in your test framework and you should fix them, instead of trying to change the spec to minimize the consequences of these flaws.

**Comment by asomov** [comment]
The spec example must clearly show the data for specified topic. If spec combines too many unrelated thing together it makes it difficult to understand the core of the problem.
This example is NOT about the order. Let us get rid of the map in favour of sequence and the issue is solved.
The spec is written for those who implemented it.
If it is the only issue - no problem. But the spec has many others.  If we are going to waste time arguing about non-issues, then no time will be left to discuss real questions. 
This fix does not change anything in the spec, it just changes the example.

**Comment by perlpunk** [comment]
I think this issue could be resolved now that there is the https://github.com/yaml/yaml-test-suite

We are working on a new revision of the spec where typos are fixed and paragraphs are clarified. Also the canonical YAML gets replaced with JSON output, where possible, as we think the canonical output does not really help implementing (but the Test Suite does).

**Comment by asomov** [comment]
too old
