### ISSUE TITLE
Is there a proper Tag URI?

### ISSUE THREAD

**Issue by trans** [yaml/yaml#2]
I see that Perl uses `tag:yaml.org,2002:perl/`. Is that expected/encouraged? Should all global tags use `tag:yaml.org,2002:`? By contrast, for example, I would have thought Ruby tags should use something like `tag:ruby-lang.org,2011/`.

**Comment by orenbenkiki** [comment]
The definition of tag URIs is that they use the (a) year where one owned
the domain in question. This neatly side-steps the issue of what happens if
the domain changes hands later on. The new owner will use a different year
(presumably, year resolution is enough :-).

We got yaml.org on 2002 so we can't use "2000". So we use "2002"
everywhere. If for some unfathomable reason martians take over yaml.org in
2013, they'll be able to use "2013", but we (the original people who owned
yaml.org at 2002) will be free to continue defining additional "2002" tags.

So the date has nothing to do with the date the type was defined at.

Have fun,

Oren Ben-Kiki

**Comment by trans** [comment]
That's good information. Thanks.

But, it's not what I was focusing on. Sorry if I wasn't clear. Rather then the year, I was curious about Perl's use of the the YAML domain name, instead of using a domain name of their own. i.e. `http://www.perl.org`

UPDATE: Ah I see the confusion now. I accidentally put `2000` instead of `2002`. I have corrected.

**Comment by orenbenkiki** [comment]
Ah. Well, the default global tag URI prefix was defined by YAML, it applies
to all the tags for all the languages...

**Comment by ingydotnet** [comment]
We standardized on yaml.org,2002/$langname/ a long time ago. It would be acceptable but not encouraged for a language to not use a different domain. Defining the tags structure is a YAML concern more than a Ruby concern.

**Comment by trans** [comment]
Is it `tag:yaml.org,2002/$langname/` or `tag:yaml.org,2002:$langname/`?  

Other then that, that answers my question! Thanks.

**Comment by orenbenkiki** [comment]
tag:yaml_._org,2002:$langname/...

**Comment by yaml-org** [comment]
I should note these URLs:

http://pyyaml.org/wiki/PerlTagScheme
http://pyyaml.org/wiki/PythonTagScheme

Excerpt: Tags in the form of '!perl/...' have a full form of
tag:yaml.org,2002:perl/....
This implies that implementation that use '!perl/...' for tagging, should
strive to stick with in the confines described in this document.
