### ISSUE TITLE
Merge arrays

### ISSUE THREAD

**Issue by tmaier** [yaml/yaml#35]
As a user, I want to be able to re-use and extend aliased arrays.

Example yaml:

```yaml
array1: &my_array_alias
  - foo
  - bar

array2:
  << *my_array_alias
  - baz
```

Expected output:
```yaml
array1:
  - foo
  - bar

array2:
  - foo
  - bar
  - baz
```

**Comment by ingydotnet** [comment]
This will probably never happen for a few reasons.

First off, merge keys for objects use regular YAML syntax. '<<' is a string key which _some_ YAML loaders perform a merge operation on, and often in a manner incompatible with other YAML loaders. Many loaders treat a `<<` key as a normal string key. Your YAML happens to be valid, but the value of `array2` is the string `'<< *my_array_alias - baz'`.

In YAML 1.3, loaders will be encouraged not to support merge keys by default. It will become an optional feature. YAML is a data language in the same sense that JSON is. Programatic features should not have ever been encouraged.

You might want to do something like this:

```
array1: &my_array_alias
  - foo
  - bar

array2:
  - <: *my_array_alias
  - baz
```

and then post process `<` keys to do what you want. Depending on your loader implementation you might be able to hook into the loading process to do that.

**Comment by tmaier** [comment]
Hi @ingydotnet, thanks for your explanation. Much appreciated.

**Comment by amomchilov** [comment]
@ingydotnet Now every application that needs this feature will have it... except it will be proprietary, and it would have wasted the developer's time. To what end?

It's absolutely acceptable to want to say "hey, this config over here is the same as the one over there, except toss this in too."

**Comment by ulope** [comment]
Please reconsider this decision. 
Yaml is used in many places where one has no control over the parsing side. 

Very common examples are:
- CI systems (Travis CI, Circle CI, AppVeyor, Jenkins, etc.).
- Docker Stack / Swarm / Compose configurations

Without the ability to merge lists complex configurations often devolve into copy&paste hells that are very difficult to maintain.

**Comment by perlpunk** [comment]
First: Yes, I can see why one would want to have such a feature. I would want it too.

Here I just want to talk about this specific suggestion in this issue.

So let's talk about merge keys for mappings first.

As @ingydotnet said, `<<` is just a string key. It's special meaning is enabled by applying a schema.
```
# implicit merge key
<<: *alias
# string key
'<<': *alias
# explicit merge key
!!merge '<<': *alias
```
That means the parser does not know anything about merging. It is not syntax.
Only the loader knows what to do with the scalar elements. It also decides if it should convert the string `TRUE` to a boolean or not.

Now to the suggested merge array.
The original suggestion was:
```
array2:
  << *my_array_alias
  - baz
```
First, this is already valid syntax. It is a simple string `'<< *my_array_alias - baz'`.
Second, to support this, we would also have to invent a completely new syntax element.
YAML syntax is already (too) complex, and suggestions for 1.3 exist to make it simpler.
From experience we know that the complex syntax and the absence of a test suite resulted in many parser differences.

I think it is not a good idea to invent a new syntax element for a single programmatic feature.

There are suggestions on how to get more generic programmatic features into YAML that would just add one new syntax element (set) and leave the implementation to a higher level.

**Comment by creatorKoo** [comment]
I really want to re-open this issue.

**Comment by bluepeter** [comment]
> I really want to re-open this issue.

+1

**Comment by 4nte** [comment]
> Please reconsider this decision.
> Yaml is used in many places where one has no control over the parsing side.
> 
> Very common examples are:
> 
> * CI systems (Travis CI, Circle CI, AppVeyor, Jenkins, etc.).
> * Docker Stack / Swarm / Compose configurations
> 
> Without the ability to merge lists complex configurations often devolve into copy&paste hells that are very difficult to maintain.
  
I can confirm, this is happening to me. I'm using both Gitlab CI & Bitbucket Pipelines, and I always end up copy/pasting blocks of configuration, resulting in huge unreadable yaml files.

+1

**Comment by perlpunk** [comment]
I think it was explained well enough that:
- We understand that merging sequences is something useful
- The proposed syntax in this issue is close to impossible. (1)

I personally understand that it would be useful to have a standard way to do this, and new features in YAML 1.3 sound nice but don't exist yet. But this issue talks about a specific syntax.

(1) Everyone who wants this syntax, feel free to implement a parser that does this. But first look at the YAML Test Matrix http://matrix.yaml.io/ and think about why we have so few parsers that are working correctly, and if you really feel able to implement a correct parser (at least as correct as existing ones) with this new feature.

**Comment by perlpunk** [comment]
I created issue #48

**Comment by tom10271** [comment]
The problem I face is I am using a framework and all I allowed is to set the config only and no control over how it parses. Native support in YAML become very important to reduce duplicated codes

**Comment by christhomas** [comment]
This is terrible reasoning. Not wanting to put symbols that mean things into the language because they are data processing? Hmmm, all symbols represent actions
```
an_array:
  - 1
  - 2
  - 3
```

Means create an array called "an_array", then each - symbol means add a numerical index to the array it's defined under with the value: 1, 2, 3

Adding <<: or whatever here is just another syntax element, just because it's data processing doesn't mean it's not worthy and this helps in a lot of really basic cases that have real world benefits.

Saying that because something is data processing, well, damn, all symbols represent data processing. All elements do things according to what the specification says it means

**Comment by perlpunk** [comment]
@christhomas I think it was already explained well that `<<` is *not* a special syntax element. To the YAML parser it's just a string.
The constructor turns it into something special (if supported and enabled).

Please read the explanations above and the linked issue #48

**Comment by christhomas** [comment]
Then it should be a special syntax element, because it is in the position of syntax and not data, << could be a part of a string, but if you're in an array syntax and you can't find a "-" or a "key:" then "<<:" is obviously not a string. 

```
this_array:
  - a sequence key
  key: a value for a mapping (key: being the key and this string is the value)
  <<: this is obviously a completely different thing
```

Each time the processor is scanning through, it's taking care of indentation, it comes to <<: and then it thinks that this is a string?

Does anybody use << as a string whilst defining arrays? Anybody? and under what conditions? I can't even think why I'd want to use << as a string key in an array

**Comment by perlpunk** [comment]
This YAML is already invalid:
```
sequence:
  - item1
  key: value
```

But let's take your `<<:` proposal:
```
sequence:
  - item1
  <<: *alias
```

This would be a new syntax, because currently this is invalid. I can give you reasons why this still isn't practicable and would need a lot of changes in existing YAML processors. An obvious problem though is: let's say you want that merge element at the top of the sequence:
```
sequence:
  <<: *alias
  - item2
```

Now the node under `sequence` will be parsed as a mapping, and the `- item2` is now invalid.

**Comment by christhomas** [comment]
I wasn't giving a single example, I was giving an array with the three possible options below it, either a sequence key (-), a mapping (key:), or a merge key (<<:)

**Comment by gavenkoa** [comment]
https://stackoverflow.com/questions/4948933/is-there-a-way-to-alias-anchor-an-array-in-yaml

**Comment by CodingMarkus** [comment]
I can understand why people want this feature, it totally makes sense for Gitlab CI & Bitbucket Pipelines, yet you are asking for this feature at the wrong address. Gitlab/Bitbucket should instead change the way how they process the pared YAML data of their config files to make such a feature possible. If Gitlab/Bitbucket would use JSON for their config files or XML, you wouldn't have such a feature either and you would certainly not ask the standard bodies of these two formats to add it just for Gitlab/Bitbucket, would you? For jobs in Gitlab for example, you can use YAML
```
SomeJob: &InheritFromSomeJob
  xxx: ...
  yyy: ...

AnotherJob:
  <<: *InheritFromSomeJob
  zzz: ...
```
But they also offer an own inheritance mechanism:
```
AnotherJob:
  extends: SomeJob
  zzz: ...
```
Thy could do the same with arrays you commonly want to extend. So as nice as such a feature would be for many developers, I can understand why the standard authors voted against it.

**Comment by unfor19** [comment]
Here's how I implement it in a [docker-compose.yml](https://docs.docker.com/compose/compose-file/compose-file-v3/) file.

The "merge array" part is in the environment variables section. I think that the tricky (and cool part) is that I was able to use the reference to `*snapshots-repository-path` in `&es-env-base`.

In general - prefer using [long syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#long-syntax-1) over [short syntax](https://docs.docker.com/compose/compose-file/compose-file-v3/#short-syntax-1) since it enables using YAML `*references`.

```docker-compose
version: "3.7"

### ------------------------------------------------------------------
### Variables
### ------------------------------------------------------------------
x-variables:
  exposed-port: &exposed-port 9200
  es-base: &es-base
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  data-path: &data-path /usr/share/elasticsearch/data      
  snapshots-repository-path: &snapshots-repository-path /usr/share/elasticsearch/backup
  volume-snapshots-repository: &volume-snapshots-repository 
    - type: volume
      source: snapshots-repository
      target: *snapshots-repository-path  
  services-es-env: &es-env-base
    "cluster.name": "es-docker-cluster"
    "cluster.initial_master_nodes": "es01,es02"
    "bootstrap.memory_lock": "true"
    "ES_JAVA_OPTS": "-Xms512m -Xmx512m"
    "ELASTIC_PASSWORD": "esbackup-password"
    "xpack.security.enabled": "true"
    "path.repo": *snapshots-repository-path
### ------------------------------------------------------------------

services:
  es01: # master
    <<: *es-base
    container_name: es01
    environment:
      <<: *es-env-base
      node.name: es01
      discovery.seed_hosts: es02
    volumes:
      - <<: *volume-snapshots-repository 
      - type: volume
        source: data01
        target: *data-path
    ports:
      - published: *exposed-port
        target: 9200
        protocol: tcp
        mode: host

  es02:
    <<: *es-base
    container_name: es02
    environment:
      <<: *es-env-base
      node.name: es02
      discovery.seed_hosts: es01
    volumes:
      - <<: *volume-snapshots-repository 
      - type: volume
        source: data02
        target: *data-path

volumes:
  data01:
    driver: local
  data02:
    driver: local
  snapshots-repository:
    driver: local

networks:
  elastic:
    driver: bridge
```

**Comment by netcazean** [comment]
#64

**Comment by netcazean** [comment]
#63

**Comment by 2colours** [comment]
@CodingMarkus I arrived here without any Gitlab and Bitbucket, simply wanting to construct structured data without hacking ad-hoc preprocessing into it. YAML is already a format that has anchors and aliases, it effectively inflates the usefulness of them that one is unable to construct an array from multiple pieces. If I need to use this bloated language AND still do custom preprocessor hacks, I might just not use it in the first place, and this is indeed the conclusion I reached.

Saying that this is a tooling problem is absolutely backwards, a clear example of not understanding what your technology was chosen for.

**Comment by 6543** [comment]
https://github.com/go-yaml/yaml/issues/421#issuecomment-1527840492

**Comment by andrewvaughan** [comment]
Can't believe this isn't part of the spec - it took me ages to figure out what was going wrong. I can't believe it was shut down this early in dev.

> [go-yaml/yaml#421 (comment)](https://github.com/go-yaml/yaml/issues/421#issuecomment-1527840492)

And now we have anti-patterns where there's so much demand, implementors are purposely deviating from the intention of the schema.

Take a hint, y'all - the community is going to make this happen 33x different ways, if you don't, and discrepancy kills usage of standards.

**Comment by paddy667** [comment]
I've been encountering the same issue in the kubernetes/devfile space. So I will just add my use case here for consideration.

I want to define common environment variables, each component in my devfile gets those common environment variables. Some componenets use all the common env vars and then need 1 or 2 additional var. What I would like to do:

```
schemaVersion: 2.2.2
metadata:
  name: my-devfile
projects:
  - name: nodejs-web-app
components:
  - name: runtime
    container:
      image: quay.io/nodejs-12
      env:
        &env_vars # Define environment variables anchor
        - name: ENV1
          value: value1
        - name: ENV2
          value: value2
        - name: ENV3
          value: value3
  - name: database
    container:
      image: postgres:latest
      env:
        <<: *env_vars # Merge base environment variables (this fails)
        - name: ANOTHER_VAR
          value: another_val
  - name: cache
    container:
      image: redis:latest
      env:
        <<: *env_vars # Merge base environment variables (this fails)
        - name: CACHE_VAR
          value: cache_val
```

Since I can't do this, I need to redefine my environment variables in each section for database and cache. As others have said this creates very large and messy YAML files.

**Comment by tom10271** [comment]
> I've been encountering the same issue in the kubernetes/devfile space. So I will just add my use case here for consideration.
> 
> I want to define common environment variables, each component in my devfile gets those common environment variables. Some componenets use all the common env vars and then need 1 or 2 additional var. What I would like to do:
> 
> ```
> schemaVersion: 2.2.2
> metadata:
>   name: my-devfile
> projects:
>   - name: nodejs-web-app
> components:
>   - name: runtime
>     container:
>       image: quay.io/nodejs-12
>       env:
>         &env_vars # Define environment variables anchor
>         - name: ENV1
>           value: value1
>         - name: ENV2
>           value: value2
>         - name: ENV3
>           value: value3
>   - name: database
>     container:
>       image: postgres:latest
>       env:
>         <<: *env_vars # Merge base environment variables (this fails)
>         - name: ANOTHER_VAR
>           value: another_val
>   - name: cache
>     container:
>       image: redis:latest
>       env:
>         <<: *env_vars # Merge base environment variables (this fails)
>         - name: CACHE_VAR
>           value: cache_val
> ```
> 
> Since I can't do this, I need to redefine my environment variables in each section for database and cache. As others have said this creates very large and messy YAML files.

Out of topic but I strongly recommend you to give Terraform a try. It is a great IaC tool. Also you can use ConfigMap and Secret to solve code duplication issue.

**Comment by Kukunin** [comment]
> Out of topic but I strongly recommend you to give Terraform a try.

I highly recommend Pulumi over Terraform. It gives way more freedom and concise syntax while being compatible with Terraform providers
