### ISSUE TITLE
Clarification over serialization process

### ISSUE THREAD

**Issue by amihaiemil** [yaml/yaml#36]
I don't really understand the scope of "serialization" as it is explained [here](http://yaml.org/spec/1.2/spec.html#id2765410). Also, see **Example 2.10**.

I mean, replacing repeated value nodes with ampersands and aliases - what is the gained value of this process?

For a parser, this means more logic and implementation effort, while for a human reader, it seems harder to understand. It is **_either a short YAML_** where there are 1-2 duplicated values, so the substitution doesn't make much sense, **_or a long YAML_** where this kind of substitution would clearly render it unreadable.

So, if anybody could point out what I'm missing, I would be really grateful. Thanks!

**Comment by amihaiemil** [comment]
@flyx Maybe you can shed some light for me, when you have time? :D

**Comment by flyx** [comment]
The reason is that YAML was designed to be a serialization language for data structures. Imagine you have a graph in your favorite programming language (Java in this example):

```Java
public class Node {
    public String name;
    public List<Node> edges;
}
```

And this graph has a cycle:

```
A -> B
^    |
|    v
C <- D
```

YAML would be able to serialize this as:

```yaml
--- &a
name: A
edges:
  - name: B
    edges:
    - name: C
      edges:
      - name: D
        edges:
        - *a
```

This would simply not be possible without this feature.

Moreover, a YAML like this:

```yaml
foo: &a myval
bar: *a
```

is structurally different from this:

```yaml
foo: myval
bar: myval
```

If you deserialize the first one with a strictly conforming implementation, *one* String object would be created and both *foo* and *bar* would point to it. If you deserialize the second one, you'd have *two* String objects. This is important as soon as you have mutable entities (which Strings in Java are not), because then it makes a difference in the semantics of your code.

**Comment by tanriol** [comment]
Also, if you're using YAML for a configuration file, it may make perfect sense for the human writing it to write explicitly "the same configuration named above". At least to remember the next time that for my use case these two need to be the same.

**Comment by amihaiemil** [comment]
@flyx @tanriol I see, many thanks for the explanations. Yes, I am looking at it more like at a configuration tool. So, small, readable configuration files, easy to understand for humans and also easy to parse for programmers :D

**Comment by perlpunk** [comment]
Looks like this can be closed
